name = "atmalink-app"
main = "src/index.ts"
compatibility_date = "2024-06-01"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "devatmalink.perluniuaj.org", custom_domain = true }
]

[assets]
directory = "../../apps/mobile-web/dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[vars]
ENV = "local"
JWT_SECRET = "atmalink-dev-jwt-secret-2026"

[[d1_databases]]
binding = "DB"
database_name = "atmajaya-db-preview"
database_id = "5c5a61da-1127-4dbc-8a70-6ba403731806"

[[kv_namespaces]]
binding = "KV"
id = "4e07ce65c49640039c616e96df373953"
preview_id = "4e07ce65c49640039c616e96df373953"

[[r2_buckets]]
binding = "R2"
bucket_name = "atmajaya-media-preview"

[durable_objects]
bindings = [
  { name = "CHAT_ROOM", class_name = "ChatRoom" }
]

[exports.ChatRoom]
type = "durable-object"
storage = "sqlite"

[env.preview]
vars = { ENV = "preview" }
routes = [
  { pattern = "devatmalink.perluniuaj.org", custom_domain = true }
]
d1_databases = [
  { binding = "DB", database_name = "atmajaya-db-preview", database_id = "5c5a61da-1127-4dbc-8a70-6ba403731806" }
]
kv_namespaces = [
  { binding = "KV", id = "4e07ce65c49640039c616e96df373953", preview_id = "4e07ce65c49640039c616e96df373953" }
]
r2_buckets = [
  { binding = "R2", bucket_name = "atmajaya-media-preview" }
]
durable_objects.bindings = [
  { name = "CHAT_ROOM", class_name = "ChatRoom" }
]

[env.production]
vars = { ENV = "production" }
d1_databases = [
  { binding = "DB", database_name = "atmajaya-db", database_id = "83bfc8bd-4e9a-4823-8e97-cdb4679b0ada" }
]
kv_namespaces = [
  { binding = "KV", id = "693e7616f606459284e0873f34b89f3c" }
]
r2_buckets = [
  { binding = "R2", bucket_name = "atmajaya-media" }
]
durable_objects.bindings = [
  { name = "CHAT_ROOM", class_name = "ChatRoom" }
]