// This file is generated by `wrangler types` – keep in sync with wrangler.toml
export interface Bindings {
  DB: D1Database;
  KV: KVNamespace;
  R2: R2Bucket;
  JWT_SECRET: string;
  // Email Workers binding (optional)
  EMAIL?: any;
  // Secrets set via `wrangler secret put`
  STRIPE_SECRET?: string;
  APNS_KEY_ID?: string;
  APNS_TEAM_ID?: string;
  APNS_PRIVATE_KEY?: string;
  FCM_SERVER_KEY?: string;
}